# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: UWynn
description: >- # this means to ignore newlines until "baseurl:"
  Wynncraft guides, utilities, and other helpful stuff.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://uwynn.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SayaDuck
github_username:  SayaDuck

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass

#theme: minima
minima:
  skin: dark
  social_links:
    github: SayaDuck
plugins:
  - jekyll-feed
collections:
  authors:
    output: true


defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

header_pages:
 - worlds.md
 - guides.md
 - about.md
 - changelog.md
 - contributors.md

# Google Analytics
google_analytics: G-WGLFZK5Q3F


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
